### ISSUE TITLE
readme.md suggests Maven 3.5 introduced activation via AND

### ISSUE THREAD

**Issue by jlmuir** [random-maven/profile-activator-extension#1]
`readme.md` says

> works with Maven 3.5 ([activation via AND](https://issues.apache.org/jira/browse/MNG-4565))

but I'm confused because the linked Maven issue says it was fixed in Maven 3.2.2, not 3.5.

So, should `readme.md` instead say "works with Maven 3.2.2 or later (activation via AND)"?

**Comment by Andrei-Pozolotin** [comment]
3.5 is later then 3.2.2 hence it also works :-) sorry about confusion
