### ISSUE TITLE
Only first profile using this extension is activated

### ISSUE THREAD

**Issue by hlzhang** [random-maven/profile-activator-extension#3]
I have multiple profiles contain groovy script in their property values.
I found that only first one was in maven log and profiles after it were not activated.

**Comment by Andrei-Pozolotin** [comment]
1. thank you for the report
2. resolved in v 1.3 https://github.com/random-maven/profile-activator-extension/releases
3. test case https://github.com/random-maven/profile-activator-extension/tree/master/src/it/issue-3
